In [3]:
import pandas as pd
%matplotlib inline

In [15]:
# URL that points directly to the police blotter dataset 
#URL = "https://data.wprdc.org/datastore/dump/044f2016-1dfd-4ab0-bc1e-065da05fca2e"
# Read the CSV files from the URL into a Pandas Dataframe and display the first 5 rows
#police_data = pd.read_csv(URL)
#police_data.head()


playgrounds = pd.read_csv("https://data.wprdc.org/dataset/640add54-b0e1-4abb-a232-f5092b243ee0/resource/40097711-aa25-47d9-b0fb-920cace3afa0/download/opendata-pubworks-play-area-listing-2015.csv")
#playgrounds.head()
landslides = pd.read_csv("https://data.wprdc.org/dataset/7db7daf4-1fcc-4ad6-ad5e-6ed21a45b154/resource/dde1f413-c849-413c-b791-0f861bf219ce/download/globallandslides.csv")
#landslides.head()
internetproviders = pd.read_csv("https://data.wprdc.org/dataset/ae1f7cda-5e15-4a8a-a5b2-2e4803f1500a/resource/c2df1e6f-5563-4e53-9de8-b0e4c7d2cb93/download/pittsburghispsbyblock.csv")
steps = pd.read_csv("https://data.wprdc.org/datastore/dump/43f40ca4-2211-4a12-8b4f-4d052662bb64")

In [17]:
playgrounds.groupby("Neighborhood").sum()
playgrounds.head()

,Play area name,Facility,Address,Neighborhood,Dedicated Park,AKA Name,Spring Rider,Modular 2-5,Modular 5-12,Modular 2-12,...,Swing Baby,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Able Long Parklet,ABLE LONG PARKLET,Coast & Gagwin St.,Beechview,Western,NaN,NaN,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Albert ""Turk"" Graham Parklet","ALBERT ""TURK"" GRAHAM PARKLET",Foreside & Vine St.,Crawford Roberts,Schenley,NaN,NaN,1.0,1.0,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sue Murray,ALLEGHENY COMMONS PARK,Ceadar Ave,Allegheny Center,State,NaN,3.0,NaN,1.0,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,M. L. King,ALLEGHENY COMMONS PARK,West North Ave.,Allegheny Center,State,NaN,NaN,1.0,1.0,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,North Ave,ALLEGHENY COMMONS PARK,West North Ave.,Allegheny Center,State,NaN,NaN,1.0,1.0,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
landslides.head()

,src_name,src_link,ev_id,ev_date,ev_time,ev_title,ev_desc,loc_desc,loc_accu,ls_cat,...,ev_imp_id,latitude,longitude,ctry_name,ctry_code,div_name,gaz_point,gaz_dist,sub_date,edit_date
0,Oregon DOT,NaN,"8,840",2011-01-16,16:00,"OR 218, milepost 34.9",NaN,"OR 218, milepost 34.9",exact,landslide,...,8840.0,44.9184,-120.2668,United States,US,Oregon,Kinzua,18.34,2016-07-08,2018-06-23
1,www.itv.com,http://www.itv.com/news/westcountry/2013-12-30...,"5,725",2013-12-25,NaN,"Calstock, Cornwall",The Army is on standby to help residents in Ca...,"Calstock, Cornwall",1km,landslide,...,5725.0,50.4972,-4.2100,United Kingdom,GB,England,Plymouth,10.57,2014-04-01,2018-06-23
2,business-standard,http://www.business-standard.com/generalnews/n...,"4,343",2012-05-01,14:00,"Shennongjia, Hubei",More than 300 tourists were evacuated after a ...,"Shennongjia, Hubei",25km,landslide,...,4343.0,31.7501,110.6807,China,CN,Hubei,Nan He,13.49,2014-04-01,2018-06-23
3,The Statesman,http://www.thestatesman.com/news/northeast/lan...,"6,964",2015-06-17,NaN,"National Highway 31A, Darjeeling Hills","Note: one article listed multiple landslides, ...","National Highway 31A, Darjeeling Hills",50km,landslide,...,6964.0,27.0087,88.4430,India,IN,West Bengal,Kalimpong,8.03,2015-06-25,2018-06-23
4,pia,http://www.pia.gov.ph/?m=12&fi=p080104.htm&no=10,408,2008-01-03,NaN,Pancho Villa and Kahupian villages in Sogod,very little information on the hazard,Pancho Villa and Kahupian villages in Sogod,25km,landslide,...,408.0,10.3904,124.9851,Philippines,PH,Southern Leyte,Sogod,0.07,2014-04-01,2018-06-23